services:
  - type: web
    name: erich-automobile-api
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && npx prisma db seed && node dist/server.js
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        value: ErichAuto2026SuperSecretKeyRender
      - key: CORS_ORIGIN
        value: https://erich-automobile-frontend.onrender.com
      - key: PORT
        value: "4000"
      - key: UPLOAD_DIR
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: "10485760"
  - type: web
    name: erich-automobile-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://erich-automobile-api.onrender.com
